title: My personal blog - Qiqin Zhou
email: qz247@cornell.edu
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my personal blog!
  Feel free to learn more about my work experience, research projects and life.
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Qiqin Zhou # add your name
author-pic: photo.jpg
about-author: My name is Qiqin Zhou. I’m a student of Master of Financial Engineering at Cornell.
  I aspire to work as a quantitative researcher / trader, data analyst, machine learning / deep learning / NLP engineer
  in leading financial and technology institutions in U.S. Get to learn more about me on the Blog!
# Contact links

email: qz247@cornell.edu # Add your Email address
phone: 1 (607) 3792441# Add your Phone number
website: # Add your website, do not add http://
linkedin: linkedin.com/in/qiqin-z-5b6a701ba # Add your Linkedin handle
github: rillsong # Add your Github handle
twitter: '@rillsong' # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier:  # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
